- src/components/patterns/algolia-course-list.tsx
> Algolia result list pattern

- src/components/paragraphs/stanford-card/card-paragraph.tsx
- src/lib/drupal/drupal-jsonapi.d.tsx
> SUM-113 - Adding card variant.

- src/components/paragraphs/stanford-card/card-paragraph.tsx
- Fixes reference to boolean for hiding the header
ASAP
> FIXUP - hide header ref

- src/components/paragraphs/stanford-card/card-paragraph.tsx
- src/components/patterns/image-card.tsx
- src/components/patterns/pill-card.tsx
- src/lib/drupal/drupal-jsonapi.d.tsx
- Theme & style basic and pill card
- Pill card dependent on https://github.com/SU-SWS/ace-stanfordlagunita/pull/100
2. Create a basic page with the default and pill cards
3. Spin up your local and review the page
4. Verify that it appears the same as the figma mocks
5. Review code 👾 
- Is there a config:export in this PR that changes the config sync directory? **Nope**
- SUM-33
- SUM-39
> SUM-33 SUM-39 | @rebeccahongsf | theme & style basic and pill card

- src/components/paragraphs/sum-testimonial-banner/sum-testimonial-banner-paragraph.tsx
- theme and style testimonial banner
2. Spin up your local
3. Create a page with a testimonial banner
4. Verify that it appears like the [responsive mock](https://www.figma.com/design/vnc2oxvzX9qZ3rK5vmjpdZ/Summer-Session-Wireframes?node-id=3293-9845&t=CXo9bzAx343NnWRc-1)
5. Review code 👾 
- Is there a config:export in this PR that changes the config sync directory? **Nope**
- SUM-37
> SUM-37 | theme and style testimonial banner

- app/layout.tsx
- src/components/config-pages/local-footer.tsx
- src/components/elements/select-list.tsx
- src/components/paragraphs/sum-calculator/sum-calculator-paragraph.tsx
- src/components/paragraphs/sum-calculator/sum-calculator.tsx
- Theme and style calculator page
2. Spin up local
3. Navigate to calculator page `/cost/tuition-fees-calculator`
4. Verify that the calculator components match the [figma mock](https://www.figma.com/design/vnc2oxvzX9qZ3rK5vmjpdZ/Summer-Session-Wireframes?node-id=4590-36334&t=CXo9bzAx343NnWRc-1) for desktop and responsive
5. Review code 👾 
- Is there a config:export in this PR that changes the config sync directory? **Nope**
- SUM-173
> SUM-173 | theme and style calculator page

- src/components/patterns/arc-banner.tsx
- src/styles/index.css
> fixup SUM 42

- .env.example
- .github/workflows/build_lint.yml
- app/[...slug]/page.tsx
> Better Github actions tests

- .github/workflows/build_lint.yml
- .gitpod.yml
> Sync gitpod with acquia

- src/components/elements/apply-now-link.tsx
- src/components/elements/wysiwyg.tsx
- src/components/nodes/pages/summer-course/summer-course-page.tsx
- src/components/paragraphs/sum-course-filter/course-filtering-form.tsx
- src/components/paragraphs/summer-user-favorite/user-favorite-paragraph.tsx
- src/styles/index.css
- add apply-now-link and left-bar wysiwyg styles
2. Navigate to Course List, Favorites, and Course pages
3. Verify that the Apply Now link block appears.
4. Create a basic page with a WYSIWYG
5. Add the following snippets to the WYSIWYG
```
<a class="apply-now-link">
Ready to dive in? Kick off your application today – let's make things happen!  
</a>
```
```
<div class="left-bar">
<h2>Brace yourself</h2>
<p>Rent can be between $2,500 to $4,000 a month in Palo Alto. We totally get the desire to hunt for a better deal off-campus, but our housing plan is tough to beat.</p>
</div>
```
6. Verify that it appears like the mocks
7. Review code 🪴 
- SUM-164 
- SUM-183
> SUM-164 SUM-183 | add apply-now-link and left-bar wysiwyg styles

- src/components/nodes/pages/summer-course/summer-course-page.tsx
- adjust course arc banner 
1. Review code
- SUM-201
> SUM-201 | adjust course arc banner

- src/components/elements/favorites-list.tsx
- src/components/elements/headers.tsx
- src/components/elements/wysiwyg.tsx
- src/components/paragraphs/sum-arc-banner/sum-arc-banner-paragraph.tsx
- adjust favorite share button disable color; adjust wysiwyg header font weight
1. Review code
- SUM-203
> SUM-203 | adjust favorite share button disable color; adjust wysiwyg header font weight

- src/components/elements/apply-now-link.tsx
- adjust thickness and offset of apply now link
1. Review code
- SUM-200
> SUM-200 | adjust thickness and offset of apply now link

- src/components/elements/back-to-top.tsx
- adjust back to top link
1. Review code
- SUM-206
> SUM-206 | adjust back to top link

- src/components/elements/select-list.tsx
- src/components/paragraphs/sum-calculator/sum-calculator.tsx
- adjust disable field color and button
1. Review code
- SUM-208
> SUM-208 | adjust disable field color and button

- src/components/paragraphs/sum-at-a-glance/at-a-glance-paragraph.tsx
- adjust at-a-glance border for wysiwyg
1. Review code
- SUM-212
> SUM-212 | adjust at-a-glance border for wysiwyg

- src/components/patterns/image-card.tsx
- adjust transparent card with image padding
1. Review code
- SUM-211
> SUM-211 | adjust transparent card with image padding

- src/components/elements/slideshow.tsx
- src/components/paragraphs/sum-carousel/sum-carousel-paragraph.tsx
- src/components/paragraphs/sum-pill-banner/sum-pill-banner-paragraph.tsx
- adjust pill banner action link, carousel disabled buttons, and arc carousel 
1. Review code
- SUM-214
- SUM-215
- SUM-216
> SUM-214 SUM-215 SUM-216 | adjust pill banner action link, carousel disabled buttons, and arc carousel 

- src/components/elements/headers.tsx
- src/components/elements/wysiwyg.tsx
- src/components/menu/main-menu.tsx
- src/components/paragraphs/stanford-banner/banner-paragraph.tsx
- fixup navigation, default banner, and sitewide headings
1. Review code
- SUM-205
- SUM-218
- SUM-219
> SUM-205 SUM-218 SUM-219 | fixup navigation, default banner, and sitewide headings

- src/components/elements/wysiwyg.tsx
- fixup conflicting typography
1. Review code
- SUM-209
> SUM-209 | fixup conflicting typography error

- src/components/paragraphs/sum-testimonial-banner/sum-testimonial-banner-paragraph.tsx
- adjust span for col
1. Review code
- SUM-213
> SUM-213 | adjust span for col

- src/components/elements/favorites-list.tsx
- src/components/paragraphs/sum-course-filter/course-filtering-form.tsx
- SUM-199 | fixup course filter page for xs screens
1. Review code
- SUM-199
> SUM-199 | fixup course filter page for xs screens

- src/components/elements/back-to-top.tsx
- src/components/elements/favorite-button.tsx
- src/components/elements/lockup/lockup-logo.tsx
- src/components/elements/shareCourses.tsx
- src/components/menu/main-menu.client.tsx
- src/components/paragraphs/sum-calculator/sum-calculator.tsx
- src/components/paragraphs/sum-course-filter/course-filtering-form.tsx
- SUM-59 | accessibility fixes
- Some fixes have been included in #54 
1. Review code
- SUM-59
> SUM-59 | accessibility fixes

- src/components/elements/youtube-video-pill.tsx
- Add play button
- Fix regex for youtube videos with `-` or `_` in their ID.
> Add play button on youtube pills

- package.json
- src/components/elements/tables.tsx
- src/components/elements/wysiwyg.tsx
- yarn.lock
> Use responsive tables for wysiwyg mobile

- src/components/paragraphs/sum-testimonial-banner/sum-testimonial-banner-paragraph.tsx
- SUM-198 | adjust testimonial image position for mobile devices
1. Review code
- SUM-198
> SUM-198 | adjust testimonial image position for mobile devices

- src/components/elements/favorite-button.tsx
- src/components/elements/shareCourses.tsx
> Switch from hocus to hocus:visible on share and favorite buttons

- src/components/config-pages/global-message.tsx
- src/components/config-pages/local-footer.tsx
- src/components/elements/lockup/lockup-a.tsx
- Adjust global message link spacing and footer link span
1. Review code
> Adjust global message link spacing and footer link span

- app/layout.tsx
- package.json
- src/components/elements/favorites-list.tsx
- src/components/elements/shareCourses.tsx
- src/components/elements/toast-message.tsx
- yarn.lock
- Designer was ok with the look.
- I changed the color of the progress bar to be spirited-light
- Updated with the feedback.
- Added a Copied! when using the copy feature for favorited classes.
- Added a Copied! when using the Copy share link on each course.
- When time
- Normal
- Normal
1. Review the Vercel link. 
2. Go to /courses and favorite some classes. 
3. Use the copy button.
4. Verify you get the copied alert.
5. Verify it stays and then disappears.
6. Verify the copy still works.
7. Try in responsive views.
8. Review the code.
9. I added react-toastify. 
10. Verify you can copy a share link for each course.
11. Verify multiple clicks to copy create stacked copied notifications and they disappear in order appeared. 
- Is there a config:export in this PR that changes the config …
> SUM-260: added react-toastify to make copied alert

- src/components/elements/button.tsx
- fixed the arrow on the secondary button. It was supposed to be red and then white on hover.
- 5/3
- Normal
- Normal
3. Navigate to any page. 
4. Verify the first top button on the right is a secondary one. The arrow is red one load and red on hover.
[- SUM-323](https://stanfordits.atlassian.net/issues/SUM-323)
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- …
> SUM-323: updated the arrow on the secondary button.

- src/components/patterns/pill-card.tsx
- Adding spacing when there is no image in a pill.
- When time
- Normal
- Normal
3. Navigate to a page and add a pill with no image
4. Verify the title and subtitle are less tight to the edge.
[- SUM-268](https://stanfordits.atlassian.net/issues/SUM-268)
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to …
> SUM-268: changing padding-top for no image pills

- src/components/elements/cookiebot.tsx
- src/lib/gql/__generated__/drupal.d.tsx
> Inform clarity of cookiebot consent

- src/components/algolia/results/summer-course/summer-course.tsx
- src/components/elements/courses-info-icon.tsx
- src/components/nodes/pages/summer-course/summer-course-page.tsx
- Adding informational icon for the prerequisites of courses. 
- Time allows
- High
- High
3. It should appear on the list of courses and individual courses. Verify the items below in both areas
4. https://summer-git-sum-336-info-stanford-summer-session.vercel.app/courses 
5. https://summer-git-sum-336-info-stanford-summer-session.vercel.app/courses/creativity-and-design/intro-making-what-ee
6. Check the text for spelling errors.
7. Navigate to courses and open details (3rd one down has the icon)
8. Verify you see the icon
9. Verify it looks correct.
10. Verify it is good on all screen sizes.
11. Verify you can tab in and out and close it.
12. Review code.
- Is there a config:export in this PR that changes …
> SUM-336: Added in an informational icon to the courses.
